### ISSUE TITLE
stream option is bad?

### ISSUE THREAD

**Issue by iliakan** [request/request-promise#104]
You write that `.pipe` is bad.

But is using a stream in a form also bad? Like this, for uploading a file:
```js
...
formData: {
  type:  'file',
  image: {
    value: stream,
  }
}
...

**Comment by analog-nico** [comment]
How does your overall piped call look like?

If I understand correctly, you are piping data INTO the request, not OUT OF the request. That would be totally ok.

**Comment by iliakan** [comment]
@analog-nico Oh, so this is ok too?

```js
stream.pipe(request.post(...)
```

What's not ok? Can you give an example or two please?

**Comment by analog-nico** [comment]
Yes, this is ok. Not ok would be:

``` js
request(...).pipe(...) // streaming the response
```

However, this case will be covered in the future as well. Subscribe to issue #90 if you want to know when it becomes available.

Are there any other stream use cases I could give you an ok/not ok for?

**Comment by iliakan** [comment]
Now I get it thanks. Did not bother to read the source and deemed all stream operations to be bad, now it's clear so I'm closing it.

**Comment by aseemk** [comment]
Hey folks, thanks for the great library and great discussions!

I too have a need to `pipe` a file _into_ a `request`. If I'm understanding this issue right, it sounds like I _can_ just do that.

I wasn't sure if I could though, since `request-promise` returns a Promise and not a `request` instance. Upon re-reading the docs though, I see I misunderstood:

> … `request-promise` wraps around `request` everything that works with `request` also works with `request-promise`.

Still, there are no examples in the docs that show doing anything with the returned object other than promise functions.

You might consider adding a `pipe`-into example to the docs, or something similar. Cheers!

**Comment by analog-nico** [comment]
Hi @aseemk , you are absolutely right. Piping INTO is totally fine. Just piping OUT OF not.

Btw, having no examples about how to handle the response other than through Promises is intentional. This will of course change once #90 gets implemented.

**Comment by xXxrAinZyian** [comment]
Ok
