### ISSUE TITLE
Can't work with uri starting with '//'

### ISSUE THREAD

**Issue by arnabdas** [request/request-promise#136]
Comes to error handler, if we try to get uri starting with '//'.

``` javascript
var rp = require('require-promise');
rp({
    method: 'GET',
    uri: '//cdn.bootcss.com/fancybox/2.1.5/jquery.fancybox.css'
}).then(function () {
    // Do something
}, function (err) {
    console.log(err);
});

// RequestError: Error: Invalid URI "//cdn.bootcss.com/fancybox/2.1.5/jquery.fancybox.css"

```
Is this expected behavior?

**Comment by analog-nico** [comment]
Yes, that is the expected behavior. I double checked it.

Since you are using this browser trick I assume you are running the code in the browser. Just use `window.location.protocol + '//cdn.bootcss.com/fancybox/2.1.5/jquery.fancybox.css'` instead.

Feel free to ask a follow up question or close this issue. Cheers!

**Comment by arnabdas** [comment]
Ok. If it's expected, then nothing to say.

Actually I was trying this from a NodeJS app. But this should work. Say in this case, it'll fallback to normal `http` protocol.

**Comment by analog-nico** [comment]
If you want to give it a try you may open an issue for your feature request over at the [`request`](https://github.com/request/request) project. This library is used by `request-promise` internally and contains [the logic to parse the uri](https://github.com/request/request/blob/master/request.js#L238).
