### ISSUE TITLE
Questions???

### ISSUE THREAD

**Issue by KpjComp** [request/request-promise#138]
I've recently been user request-promise, and have a few questions.
1.  I've noticed it depends on lodash,  but lodash is a bit of a monster module and looking at your code it might be nicer to use the module based lodash..  eg.. lodash.foreach  etc..
2.  I've also noticed you hack the require.cache so you can get an unaltered request instance, is there a reason you can't just do  new request() here?

**Comment by analog-nico** [comment]
1. Regarding Lodash: I am glad you asked. Finally someone who appreciates my obsession with details. ;) Actually, the full `lodash` library gets installed but never fully required with `require('lodash')`. The code always only requires single functions, e.g. [`require('lodash/isObjectLike')`](https://github.com/request/promise-core/blob/master/lib/plumbing.js#L5) or [`require('lodash/isString')`](https://github.com/request/promise-core/blob/master/lib/plumbing.js#L6). We could use the packages [`lodash.isObjectLike`](https://www.npmjs.com/package/lodash.isobjectlike) or [`lodash.isString`](https://www.npmjs.com/package/lodash.isstring) but if you look as `isString`'s [code](https://github.com/lodash/lodash/blob/4.0.1-npm-packages/lodash.isstring/index.js#L74-L76) you find the `isObjectLike` function included there as well. Many Lodash function have a lot of overlap. Using the independent packages for each function would introduce loading duplicated code. And since many users use Webpack or Browserify this adds unnecessary weight. Additionally, it is also relevant which Lodash function to choose. For example, to check if a variable is an object we have [`isPlainObject`](https://github.com/lodash/lodash/blob/4.0.0-npm-packages/lodash.isplainobject/index.js), [`isObject`](https://github.com/lodash/lodash/blob/4.0.0-npm-packages/lodash.isobject/index.js), and [`isObjectLike`](https://github.com/lodash/lodash/blob/4.0.0-npm-packages/lodash.isobjectlike/index.js). The safest way would be to use `isPlainObject` but if you look at the [code](https://github.com/lodash/lodash/blob/4.0.0-npm-packages/lodash.isplainobject/index.js) you see that it is huge. However, the use case actually allow a less stringent checking so I chose `isObjectLike` with the [smallest footprint](https://github.com/lodash/lodash/blob/4.0.0-npm-packages/lodash.isobjectlike/index.js).

2. Regarding `require.cache`: If a project used `request` for a long time and they want to start using `request-promise` they would need to migrate the whole codebase including all their libraries to `request-promise` if the `require.cache` technique wasn't in place. They couldn't just introduce `request-promise` for parts of their codebase. To ease the migration this technique is used. Btw, nowadays the logic is extracted into the [`stealthy-require`](https://github.com/analog-nico/stealthy-require) package. The reason why this problem arises is that `request-promise` is not a wrapper of `request` because a wrapper would have a hard time replicating the whole API that `request` exposes. To guarantee that `request`'s full API is also available to `request-promise` users, `request-promise` extends `request`'s prototype. However, to not interfere with the codebase that is using `request` directly, `request-promise` needs its own separate copy of `request` and that is only possible using the `require.cache` technique.

I hope this answers your questions.

**Comment by KpjComp** [comment]
1. isObjectLike function included there as well. Many Lodash function have a lot of overlap. 

I think the overlap is deliberate, and actually is helpful to webpack.
In your example they would be no saving on such a small function, eg.
`var isObjectLike = __webpack_require__(10)`, is nearly as long as `function isObjectLike(value) { return !!value && typeof value == 'object';}`   And after uglifying could be taken out totally and get a performance boost as it could then be inlined.  I don't believe webpack would inline _webpack_require's as it would not be local scope.  

Other advantages of npm modules, is if say 1 function got updated, you only have to npm update this one, and not the whole lodash lib.

The only reason I spotted this lodash monster lib, was I created a simple directory sync using request-promise, and after one of my work mates npm install'ed it, I thought what the monkey's is it installing, the application I created was very simple one, didn't expect that.


2. The reason why this problem arises is that request-promise is not a wrapper of request because a wrapper would have a hard time replicating the whole API that request exposes.

I'm not sure using a wrapper would require too much replicating.
Below is a simple example, here I've applied the promise functions & you still have pipe etc.  I think the defaults function would need re-implementing, as it would end up returning old class.  But apart from that, not sure what else.

```javascript
var
    bluebird = require('bluebird');

function MyRequest(options) {
    var r = request.call(this, options, callback),
        _resolve, _reject;
    function callback(error, response, body) {
        if (error) _reject(error);
        else _resolve(response);
    }
    var Prom = new bluebird(function (resolve, reject) {
        _resolve = resolve;
        _reject = reject;
    });
    r.then = Prom.then.bind(Prom);
    r.finally = Prom.finally.bind(Prom);
    r.catch = Prom.catch.bind(Prom);
    return r;
}
```

**Comment by analog-nico** [comment]
1. Regarding `lodash`: Well, it does use approx. 4MB out of the 10MB you need to save on disk for `request` + `request-promise`. However, is there a practical reason where you need to reduce the disk usage?

2. Regarding the wrapper approach: Unfortunately, it is not as straight forward. Back in November 2014 we decided to switch from the wrapper approach to the one we still have today. Not only because it is easier to implement while guaranteeing full compatibility but also to easily keep up with any new features `request` might release. Fyi, this approach will retire in the foreseeable future. The next version of `request`  is designed from the ground up to allow to be extended. There is an [alpha version](https://github.com/request/request-promise/blob/next/lib/rp.js) in case you want to take a look.

**Comment by analog-nico** [comment]
Hey @KpjComp , how are you doing? I think we have one loose end in our discussion in regard to the disk space usage of `lodash`. If you can share your arguments why having less disk space usage is very important I am happy to look closer at disk space usage vs. module bundler output size.

**Comment by KpjComp** [comment]
Hi, @analog-nico, 

I think it's mainly me been old school  :),  having any redundant code makes me feel un-easy.

But were size / number of files can have an impact is say with embedded OS's, or USB install's etc.
And say I created lots of shrink wrapped utility function's, each small utility then has this overhead.

Going forward, if the new 'request` lib is going to be modular, it would seem both issues,  would become mute anyway.  So is probably best left as is.

>>  disk space usage vs. module bundler output size.

I'm not 100% sure that one, effects the other in a big way.  Eg. like I mentioned with the option of inlining, and the __webpack_require__ overhead.  I'm assuming the functions lodash used internal were picked because of this balance.  I've not looked at everything in the lodash source, but do you know of any large duplicated functions in lodash.xyz?

An interesting point here,.  Looking at NPM there are a lots of modules that use lodash.XYZ, and other's that use the lodash and might then be using lodash/XYZ,.  In some respect's I wish lodash had chosen only one option :), As if I now do bundle the chances are I'm going to get duplicated code for this reason. IOW: It's become fragmented.

**Comment by analog-nico** [comment]
Alright, I leave it as it is. `request-promise-core` requires the full `lodash` but accesses each function specifically. This way we get the lowest possible size when using a module bundler.
