### ISSUE TITLE
Arrays POSTed arrive as Objects

### ISSUE THREAD

**Issue by lewiswalsh** [request/request-promise#144]
I send the following array using options.form:
```
[
   { item_id: 'ciqrx3zke0000wg01bvk5zohy',
    di_type: 'd',
    drop_id: 'cirntklou0001jg18vd2oxsod' },
   { item_id: 'ciqrx3zke0000wg01bvkhgaef',
    di_type: 'd',
    drop_id: 'cirntklou0001jg18vd2oxsod' } 
]
```
When it arrives in Express it's parsed as an Object:
```
{ 
  '0':
   { item_id: 'ciqrx3zke0000wg01bvk5zohy',
     di_type: 'd',
     drop_id: 'cirntklou0001jg18vd2oxsod' },
  '1':
   { item_id: 'ciqrx3zke0000wg01bvkhgaef',
     di_type: 'd',
     drop_id: 'cirntklou0001jg18vd2oxsod' }
}

```
My code expects to receive an array, as was sent. What's going on?

**Comment by analog-nico** [comment]
Since `request-promise` only forwards the `form` option to `request` – which does the heavy lifting for `request-promise` – you could ask the [`request` community](https://gitter.im/request/request) about that.

Did you read the details how [work with forms](https://github.com/request/request#forms)? Additionally, I would activate the [debugging output](https://github.com/request/request-promise#debugging) to see what request is actually sent to the server.

**Comment by lewiswalsh** [comment]
Thanks for the help. Due to the info you pointed to I tracked the issue down to the server using body-parser, which was interpreting the body as urlencoded form and not JSON. All fixed now.

**Comment by analog-nico** [comment]
Great! You are welcome.
