### ISSUE TITLE
socket hanp up error

### ISSUE THREAD

**Issue by FTAndy** [request/request-promise#161]
Error message:
```
RequestError {name: "RequestError", message: "Error: socket hang up", cause: Error: socket hang up at createHangUpError (_http_client.js:252:15) at Socket.socketOnEnd (_…, error: Error: socket hang up at createHangUpError (_http_client.js:252:15) at Socket.socketOnEnd (_…, options: Object…}
cause
:
Error: socket hang up at createHangUpError (_http_client.js:252:15) at Socket.socketOnEnd (_http_client.js:344:23) at emitNone (events.js:91:20) at Socket.emit (events.js:185:7) at endReadableNT (_stream_readable.js:974:12) at _combinedTickCallback (internal/process/next_tick.js:74:11) at process._tickCallback (internal/process/next_tick.js:98:9)
error
:
Error: socket hang up at createHangUpError (_http_client.js:252:15) at Socket.socketOnEnd (_http_client.js:344:23) at emitNone (events.js:91:20) at Socket.emit (events.js:185:7) at endReadableNT (_stream_readable.js:974:12) at _combinedTickCallback (internal/process/next_tick.js:74:11) at process._tickCallback (internal/process/next_tick.js:98:9)
message
```

Since I can't find any way to solve this, the server side or client side. But when I turn to fetch, every thing is ok. I give up using request-promise. Instead I use fetch to do all the request. Oh y!

**Comment by analog-nico** [comment]
Well, a socket hang up is an issue on the TCP layer and may be caused by either the client or the server. Since fetch is working it is somehow related to the client. However, you seem to use browserify to run `request-promise` in the browser. This means that the cause may not lie within `request-promise` nor `request` but browserify's shim for the `http` module.

You are not necessarily facing a bug in any of these libraries but would have to tweak the settings for the low level TCP behavior correctly. However, since you have fetch working - limited browser support aside - you are probably better off sticking to this approach.

**Comment by hui9464** [comment]
headers:
    {
        'Connection': 'Keep-Alive',
    },

**Comment by nirmalantony** [comment]
Adding the header 'Connection': 'Keep-Alive' is not solving this issue. Facing the issue locally and on aws workspace. Even without proxy, the issue exist
