### ISSUE TITLE
Unhandled rejection StatusCodeError: 400 when using library

### ISSUE THREAD

**Issue by Pau1fitz** [request/request-promise#168]
I am using [request-promise node module][1]. I have been following the docs, and believe I should have set everything up correctly, however, I am getting the following error:

> Unhandled rejection StatusCodeError: 400 - "{\n  \"error\" : {\n   
> \"status\" : 400,\n    \"message\" : \"invalid id\"\n  }\n}"
>     at new StatusCodeError (/Users/fitz035/Desktop/sony/travelLand/node_modules/request-promise/node_modules/request-promise-core/lib/errors.js:32:15)

My code looks like the following.

    var request = require('request');
    var rp = require('request-promise');

    rp('apiOne' + mood)
      .then(function(error, response, body) {
        console.log(body)
        }
      }).then(function(error) {
        for (var i = 0; i < array; i++) {
          rp('apiTwo', function(error, response, body) {
            console.log(body))
          });
        }
      }).then(function(error, response, body) {
        rp('apiThree' + songListUrl, function(error, response, body) {
          console.log(body))
        });
      })
      .catch(function(err) {
        console.log(err)
      });

Can someone spot what I am doing incorrectly?

  [1]: https://www.npmjs.com/package/request-promise

**Comment by analog-nico** [comment]
Hey @Pau1fitz , your issue is about Promise usage in general. What you need is to use `return` to properly tie the Promise chain together.

In particular, if `rp('apiThree'...)` responds with a 400 you get an unhandled rejection because it is not tied to your main Promise chain - that is `rp('apiOne'...).then(...).then(...).catch(...)`. Use `return rp('apiThree'...)` and the 400 will be forwarded to `.catch(...)` as expected.

It is a little bit more complicated for your loop around `rp('apiTwo'...)` because you can't just add `return`. By using a special behavior of Bluebird you can execute all `rp('apiTwo'...)` in parallel. If any of those gets rejected the error will be forwarded to `.catch(...)`.

``` js

    .then(function () {
        let calls = []
        for (var i = 0; i < array; i++) {
            calls.push(rp('apiTwo', function(body) {
                console.log(body))
            }));
        }
        return calls; // Bluebird will detect a list of Promises and deal with them in parallel before moving on to the next .then(...)
    })

```

**Comment by Pau1fitz** [comment]
thanks for the response @analog-nico. I actually got it working somewhat, although I will need to add what you have explained above, but I am now having trouble with the response. From what I have seen I need to use `transform`

**Comment by analog-nico** [comment]
Perfect. Feel free to ping me again if you have more questions. You may also use [Gitter](https://gitter.im/request/request-promise) if you want.

**Comment by sabarish14** [comment]
@Pau1fitz  Im also having the similar issue. How did you get it working?

**Comment by subhajitmishra** [comment]
Unhandled rejection StatusCodeError: 404 - "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>Cannot POST /parse</pre>\n</body>\n</html>\n"

**Comment by Pau1fitz** [comment]
@sabarish14 I have no idea, I can't remember now :-(
