### ISSUE TITLE
How to save downloaded binary data without using pipe

### ISSUE THREAD

**Issue by Aranir** [request/request-promise#171]
On my node server and try to download a png image from a url and write it to a file:

```
  request
.get("https://url/for/png/file")
.on('error', function(err) {
  console.log(err)
})
.on('response', function(response){
  console.log(response.statusCode) // 200
  console.log(response.headers['content-type']); // 'image/png'
})
.on('complete', (resp: http.IncomingMessage, body: string | Buffer) => {
  fs.writeFile(".../test.png", body, 'binary');

});
```
The main issue is that the written file is corrupted (can't be opened).

If I use pipe instead of on('complete'...) at the end the written file is correct.

```
.pipe(fs.createWriteStream(".../test.png"))
```

What exactly is the difference and what am I missing to be able to write the file?

**Comment by analog-nico** [comment]
Hi @Aranir , please do not use `request-promise` for streaming the response. See the first bullet point [here](https://github.com/request/request-promise#api-in-detail) for more explanation.

Instead, please use the `request` library directly for that purpose. Btw, you may use `request-promise` and `request` side by side. This way you can benefit from `request-promise`'s capabilities for all your other requests where you don't download a lot of data. In the future `request-promise` will properly support streaming the response as well. You may subscribe to [this issue](https://github.com/request/request-promise/issues/90) to get notified.

To get an answer for your question please read the [`request` docs](https://github.com/request/request#streaming) and ask the `request` community.

I am closing this issue because there is nothing I can do for you. But feel free to ask follow-up questions.

**Comment by Lord-Protector** [comment]
@Aranir it's too late maybe, but here is my solution
```javascript
const options = {
  url: https://url/for/png/file,
  encoding: null
};

request.get(options)
  .then(function (res) {
    const buffer = Buffer.from(res[i], 'utf8');
    fs.writeFileSync('/some/path', buffer);
  });
```

**Comment by raine** [comment]
^

`Buffer.from(res, 'utf8')` is not necessary since passing `encoding: null` as option would already make `res` a `Buffer`.

**Comment by boutell** [comment]
If you are using `resolveWithFullResponse`, then setting `encoding` to `null` will make `res.body` a buffer.

**Comment by newhouse** [comment]
I just wanted to say thank you to @L11R @raine @boutell for putting this all up here. Helped me come up with a clean looking solution where I have to "pipe" an image from a URL to a POST upload endpoint. Here's pseudo (not tested since I had to port it over from my actual code, but you get the gist):
```
const getImageOptions = {
  url: 'https://news.nationalgeographic.com/content/dam/news/photos/000/755/75552.ngsversion.1422285553360.adapt.1900.1.jpg',
  encoding: null,
  resolveWithFullResponse: true
};

const uploadImageOptions = {
  url: '<your upload url here>'
};

request.get(getImageOptions)
  .then(res => {
    // Get the content-type of whatever it is that we just grabbed off the interwebs
    // and use that in the subsequent upload request.
    postImageOptions.headers = { 'content-type': res.headers['content-type'] };
    // `res` will be a `Buffer`, so we'll pass that right though to the post
    postImageOptions.body = res.body;

    return request.post(uploadImageOptions);
  })
  .then(res => {
    // Have to JSON.parse this because you can't pass 'json: true' as an option if you
    // are sending a Buffer (or non-JSON-stringifiable data). Upvote this and maybe
    // something can be done:
    // https://github.com/request/request/issues/2692
    res = res && JSON.parse(res);
  });
```

**Comment by maikokuppe** [comment]
> @Aranir it's too late maybe, but here is my solution:
> 
> ```js
> const options = {
>   url: 'https://url/for/png/file',
>   encoding: null
> };
> 
> request.get(options)
>   .then(function (res) {
>     const buffer = Buffer.from(res, 'utf8');
>     fs.writeFileSync('/some/path', buffer);
>   });
> ```

`encoding: null` saved my day!

**Comment by irimiab** [comment]
`encoding: null` also saved my day! And I spent a couple of hours searching for a way to get the response body as buffer, in order to be able to "gunzip" it.
