### ISSUE TITLE
transforming errors when returning request directly

### ISSUE THREAD

**Issue by jmls** [request/request-promise#185]
I have this function

```
find (options) {
        options = options || {};
        let req = {
           uri: `${config.baseURL}/foo`,
            headers: {
                'Accept': 'application/json',
                'User-Agent': 'node-dashboard'
            },

            json:true
       }
        return this.request(req);
    }
```
the backend returns the message `this is foobar` as the `error`

however, the function calling `find` is getting the error `422` with a message `422 - "this is foobar"`

how can I get request-promise to return the raw error without transforming it, or having to wrap each `this.request()` with a resolve/catch block ?

**Comment by analog-nico** [comment]
@jmls I am not sure if everything is right with you setup. Could give me your stacktrace and the code of your function that calls `find`?

**Comment by jmls** [comment]
I added `request-debug` to the mix

this is the response to a `put` that returns an error

```
{ response: 
   { debugId: 1,
     headers: 
      { date: 'Sun, 23 Apr 2017 11:09:35 GMT',
        server: 'Apache/2.4.20 (Win64) OpenSSL/1.0.2h',
        vary: 'Authorization',
        connection: 'close',
        'transfer-encoding': 'chunked',
        'content-type': 'text/json' },
     statusCode: 422,
     body: 'This action can only be performed by an Administrator or the \'Sysop\' user } }
```

the code calling the "put" is

```
Workspace.save = (workspace,options:any = {}) => {
        return api.save(workspace,options).catch((e) => { 
console.log("got error e",e);
    };
```

and the output is

```
got error e { StatusCodeError: 422 - "This action can only be performed by an Administrator or the 'Sysop' user"
    at new StatusCodeError (/mypath/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/mypath/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/mypath/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/mypath/node_modules/request/request.js:188:22)
[snip]
name: 'StatusCodeError',
  statusCode: 422,
  message: '422 - "This action can only be performed by an Administrator or the \'Sysop\' user"',
  error: 'This action can only be performed by an Administrator or the \'Sysop\' user',
```
as you can see, at this point the `message` already has the "422 - <errmsg>"

**Comment by analog-nico** [comment]
Sorry, I am not sure if I understand correctly what your intend is. Do you want to get the original error instead of the `StatusCodeError`? If that is the case then check out [its definition](https://github.com/request/promise-core/blob/master/lib/errors.js#L22-L37). `err.statusCode`, the full response `err.response`, and the options you passed to the request `err.options` may be what you are looking for.

From the request perspective `StatusCodeError` is not really an error but a response with a non-2xx status code. If you don’t want the promise to be rejected for non-2xx status codes then you may consider the `simple = false` option. Then [the promise only gets rejected for technical reasons](https://github.com/request/request-promise#get-a-rejection-only-if-the-request-failed-for-technical-reasons).

Does this help?

**Comment by jmls** [comment]
I want the `message` property of the error not to have the `422 - ` embedded. I already know the error code statusCode = 422, so why would I want it as part of the message as well

**Comment by analog-nico** [comment]
I see. You know about the status code because you are accessing `err.statusCode`. But imagine a system setup in which errors are monitored in a generic way. Those error monitoring subsystems don’t necessarily deal with error specific properties. What they do, however, is processing the `message` because this attribute is provided by all error types. Therefore the status code must be mentioned in the message.

The message will [change soon](https://github.com/request/promise-core/pull/3). It won’t contain the body text anymore because that raises security concerns in large setups that use generic error monitoring. For your purposes please use `err.statusCode` and `err.response.body`. You might use `err.error` instead of `err.response.body` but `err.error` is a legacy attribute and may be dropped in future versions.

I hope this clarifies your concerns. Feel free to ask follow-up questions.
