### ISSUE TITLE
Unhandled rejection error: StatusCodeError: 401 (Unauthorized: Access is denied due to invalid credentials)

### ISSUE THREAD

**Issue by pfftdammitchris** [request/request-promise#191]
This page shows JSON inside plain empty html/body tags. For example:

    <html>
      <body>
        **JSON DATA ***
      </body>
    </html>

I can access that page fine doing it normally within a browser. But, when I send a request it says that my credentials are invalid (The response error is pretty much in the title).
And here is the code

    import dotenv = require('dotenv');
    dotenv.config({ path: '../logins.env' });
    import rp = require('request-promise');
    const jsonUrl = `http://availability.emodal.com/ImportAvailability/GetContainerInfoList?sgrdModel=%7B%22searchtext%22:%22%22,%22page%22:1,%22pageSize%22:280,%22sortBy%22:%221%22,%22sortDirection%22:%22asc%22,%22sortColumns%22:%22%22%7D`;
    
    const authOpts = {
      uri: jsonUrl,
      auth: {
        user: process.env.EMODAL_id,
        pass: process.env.EMODAL_pw,
        sendImmediately: false
      },
      method: 'get'
    }
    
    rp(authOpts)
    .then(resp => {
      console.log(resp);
    }).catch(err => { throw Error(err)});

I tried changing everything around. Like adding headers, or putting json: true, or changing sendImmediately to true. Nothing works. What am I not understanding or what am I doing wrong?

Here is an image showing the error in terminal:
[![enter image description here][1]][1]

Thank you

  [1]: https://i.stack.imgur.com/5dJON.png

**Comment by analog-nico** [comment]
How exactly does your server expect to receive the credentials? As query string? As headers?

**Comment by pfftdammitchris** [comment]
I have no idea but I found this:


![login](https://cloud.githubusercontent.com/assets/20717348/26158699/68c80052-3ad1-11e7-8968-ce3b301cb537.PNG)
![validatewharfageuser](https://cloud.githubusercontent.com/assets/20717348/26158701/68dfd506-3ad1-11e7-87f7-c7aeef91dfc4.PNG)

**Comment by analog-nico** [comment]
Ok, it seems you need to login first by sending the credentials via JSON. Then you get a cookie with which you can authenticate API requests. But this is really just a theory.

Here are the necessary pointers for these steps:
- [Sending JSON data](https://github.com/request/request-promise#post-data-to-a-json-rest-api) for the login request
- [Include the cookie](https://github.com/request/request-promise#include-a-cookie) in the second request. But instead of creating the cookie like the example shows, create an empty cookie jar and add it to the login request as the `jar` option. This way the first request will add the returned cookie to the jar and when you are using the jar in the API requests the cookie will be sent along.
