### ISSUE TITLE
Exposing Bluebird reference - Objections for pull request?

### ISSUE THREAD

**Issue by LennardF1989** [request/request-promise#214]
I'm trying to use this library in an Electron app with node.js integration disabled in the BrowserWindow context, in combination with Angular 1.x. In order to have Angular properly respond to promises coming from the node.js from within Electron itself, I have to call `Bluebird.setScheduler` in order to notify Angular about changes.

After trying lots of things, I eventually settled on modifying the rp.js-file from this library to include the following:
```
request.promise = function RP$promise() {
    return Bluebird;
}
```

I can then do something like this (where `schedulerCallback` comes from within the BrowserWindow context):
```
return rp.promise().setScheduler(schedulerCallback);
```

It's either this, or manually wrapping everything that goes into a promise inside a `$scope.apply` from Angular, which is simply annoying and code clutter.

I was wondering if there are any objections to adding these 3 lines to this project? If not, I'll happily make a pull request for it. Otherwise I'm curious to what another possible way to get the same thing done would be?

**Comment by analog-nico** [comment]
Since `request-promise` creates its own `bluebird` prototype and doesn’t expose it we would need to extend `request-promise` to allow your use case. The only other choices are that you build your own `request-promise` clone on top of [`request-promise-core`](https://github.com/request/promise-core) or you use [`request-promise-any`](https://github.com/request/request-promise-any) which allows you to inject your own `bluebird` prototype.

What is the current status of your project? Are you still looking for this solution?
