### ISSUE TITLE
Incorrect documentation at Post formData

### ISSUE THREAD

**Issue by c88lopez** [request/request-promise#230]
According to https://github.com/request/request-promise#post-like-html-forms-do

When I pass the parameters using the formData property, it would send an application/x-www-form-urlencoded but, instead, it send a multipar one. But, if rename formData => form, it send the headers properly.

**Comment by ssbrewster** [comment]
It looks like it is a doc issue but it would be good to get confirmation on that.

**Comment by c88lopez** [comment]
ok, no problem. If there is something I can do to fix this, let me know.

**Comment by analog-nico** [comment]
Hey guys, indeed it was a doc issue and I just updated the [cheat sheet](https://github.com/request/request-promise#post-like-html-forms-do) to reflect that. `formData` is a little bit more powerful than `form` because it also allows file uploads. Thus it uses a different header.

Thanks for pointing that out!
