### ISSUE TITLE
Unhandled Rejection... but I thought I had handled it?

### ISSUE THREAD

**Issue by chukkwagon** [request/request-promise#237]
I have the following code:

```
const request = require('request-promise');

function checkAuth(){
  let options = {
    url: `${config.notify_me.url}/api/login`,
    method: 'GET',
    headers: {
      Authorization: `Token ${getAuthToken()}`
    }
  };
  return request(options);
}

app.on('window-all-closed', () => {
  return checkAuth()
  .catch(err => {
    if(process.platform !== 'darwin') {
      app.quit();
    }
  });
});

```

And I am getting: `Unhandled rejection StatusCodeError: 401 - "{\"detail\":\"Invalid token.\"}"`. The invalid token is expected. I am trying to handle the case where the token is invalid by shutting down the application. 

My understanding was that the `.catch` was "handling" the exception. What am i missing here? Thanks!

**Comment by jean-moldovan** [comment]
How about you put a `console.log` beofre & after `app.quit()`, does it get there?

**Comment by chukkwagon** [comment]
Hey @jean-moldovan, I added some simple logging as you suggested and it does reach before and after the `app.quit()`. Also, I can remove `app.quit()` entirely and just log in the `.catch` and I still get the stack trace for an unhandled exception.

### Added Logging
```
return checkAuth()
.catch(err => {
  console.log('derp');
  if(process.platform !== 'darwin') {
    app.quit();
  }
  console.log('lerp');
});

// logging output (truncated)
> derp
> lerp
> Unhandled rejection StatusCodeError: 401 - "{\"detail\":\"Invalid token.\"}"
```
### Removing `app.quit()`
```
return checkAuth()
.catch(err => {
  console.log('derp');
});

// output (truncated)
> derp
> Unhandled rejection StatusCodeError: 401 - "{\"detail\":\"Invalid token.\"}"
```
Thanks for taking the time to look at this.

**Comment by ropaolle** [comment]
Same issue for me. However the section _Gotchas when throwing errors_ on page https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch says

> // Errors thrown inside asynchronous functions will act like uncaught errors

Not sure if this is related though.

**Comment by analog-nico** [comment]
Great find @ropaolle ! But this is indeed something about not having a `.catch(...)`. Saying “unhandled *rejection*” instead of “error” gives it away.

@chukkwagon I assume, your issue is outdated by now. Did you find a solution after all?

For everyone finding this: I think the cause is not visible here since the code is most likely simplified. If you get an “unhandled rejection” then make sure that you:
1. actually have a `.catch(...)`
2. that you call the `.catch(...)` synchronously. If you have an async step between `request(options)` and calling the `.catch(...)` then you can get the unhandled rejection because the catch handler was not attached soon enough.

**Comment by chukkwagon** [comment]
Yea this was some time ago, and I'm almost certain this was due to developer error / a fundamental misunderstanding of promise rejection on my part. Thank you for circling back to this!

**Comment by analog-nico** [comment]
My pleasure @chukkwagon ! I have to say, this error in particular is quite confusion since it points to a very subtle aspect of how promises work. Pretty advanced stuff. Happy coding Charlie!
