### ISSUE TITLE
request-promise@4.2.2 has unmet peer dependency request@^2.34

### ISSUE THREAD

**Issue by nypinstripes** [request/request-promise#242]
Hey was just curious if you were aware of the unmet dependency for the latest request@^2.8.3, and if you know if there are breaking changes or not. 

```
warning " > request-promise@4.2.2" has unmet peer dependency "request@^2.34".
warning "request-promise > request-promise-core@1.1.1" has unmet peer dependency "request@^2.34".
```

thanks

**Comment by nypinstripes** [comment]
@analog-nico great simplified client lib btw. ;)

**Comment by ninhxuanluu** [comment]
I got an error too.

**Comment by doublemcz** [comment]
+1

**Comment by analog-nico** [comment]
The unmet peer dependency is by design. Well, not that you actually get this error. But as the [installation instructions](https://github.com/request/request-promise#installation) say, please install `request` manually beforehand.

As for possible breaking changes in the `request` versions, I have to refer you to `request`‘s [changelog](https://github.com/request/request/blob/master/CHANGELOG.md).
