### ISSUE TITLE
Webpack - CORS error

### ISSUE THREAD

**Issue by elochai90** [request/request-promise#245]
When I use webpack to build my app and run simple requests I get the following error:

"Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access. The response had HTTP status code 401"

Even the code snipped for the google request (see [README.md](https://github.com/request/request-promise#crawl-a-webpage)) fails in the browser.

**Running my app via node (i.e without webpack) works fine though.**

Can anyone help me on this error? 

My webpack.config is:

module.exports = {
  entry: './index.js',

  output: {
    filename: './bundle.js'
  },

  node: {
    console: false,
    fs: 'empty',
    net: 'empty',
    tls: 'empty'
  }
};

**Comment by ubermensh** [comment]
Same error. And what is interesting, in network tab of browser I get 200 ok and the content I need. but it is not avaliable in code somehow.

**Comment by welll** [comment]
@elochai90 , you are missing the whole idea behind the XMLHttpRequest requests. It doesn't support perform a `request` to a different domain by default. If your page was loaded from `www.myexample.com:8080/index.html`, all the requests should be to the same host, otherwise it will fail with the CORS error.

You can inspect the generated code from Webpack/Browserify and you will see the call to XMLHttpRequest.

You can read more about the XMLHttRequest and about CORS:
- https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest
- https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by analog-nico** [comment]
Correct. It’s a CORS issue that isn’t caused by wrong code but by the network setup and thus the web security kicking in. What the error message says is that the server, to which the request was sent, only allows access from certain locations. Your client is not listed in these locations. Google the error message and you’ll can get a handle of understanding what is happening from a web security standpoint.
