### ISSUE TITLE
Request-promise error wrapping

### ISSUE THREAD

**Issue by tosbaha** [request/request-promise#253]
I am mocking `request-promise` with **nock** library. If I `replyWithError` and throw `Error: something awful happened` and in the mocking, catch block gets `RequestError: Error: something awful happened` 

Is this intended behaviour? 

It is like every error thrown in request-promise is wrapped and all errors are put into as string in RequestError.message.

**Comment by analog-nico** [comment]
Yes. That is intended.

Well, it’s not like this for all errors. It rather seems this way because of how you mocked the library. All errors that are thrown by the underlying `request` library are indeed wrapped into a `RequestError`. But there are also other error types like a `StatusCodeError` that `request-promise` introduces.
