### ISSUE TITLE
`err.code` for `ETIMEDOUT` errors

### ISSUE THREAD

**Issue by iliocatallo** [request/request-promise#262]
Hi,

According to the `request` [documentation](https://github.com/request/request#timeouts),  errors due to timeouts should feature a `code` and `connect` property. However, when using `request-promise` such properties seem `undefined`. 

Am I missing something?

Thanks,
Ilio.

**Comment by aguegu** [comment]
same problem. the `err.code` is `undefined`, even if it is a 4xx response

**Comment by bnfrnz** [comment]
It's `err.cause.code` or `err.error.code`:

```
Error: {
  "name": "RequestError",
  "message": "Error: ETIMEDOUT",
  "cause": {
    "code": "ETIMEDOUT",
    "connect": true
  },
  "error": {
    "code": "ETIMEDOUT",
    "connect": true
  },
  ...
}
```

**Comment by iliocatallo** [comment]
Doesn't this break the expectation of `request-promise` mirroring `request`'s public API?

**Comment by bnfrnz** [comment]
I suppose it does.

It seems like the `RequestError` is wrapped in an `Error`.

I should add that I'm catching the above quoted object when using `simple: false` ([Get a rejection only if the request failed for technical reasons](https://github.com/request/request-promise#get-a-rejection-only-if-the-request-failed-for-technical-reasons)). I'm not sure whether or not that changes anything though.

Just stringify and log your error and have a look what you're getting...

**Comment by iliocatallo** [comment]
While one can always inspect the error object and find out by himself, maybe it would be more beneficial to mention in the documentation so as to make explicit that there are some cases in which `request-promise`'s behaviors diverges from that of `request`.

**Comment by analog-nico** [comment]
Great discussion! As you see above I just added an additional note in the docs to mention the error wrapping. Btw, there is also a code example that shows how errors are processed when you look at it from a pure `request` perspective: https://github.com/request/request-promise#thenonfulfilled-onrejected

Indeed, at this point `request-promise` starts to differ from `request`. Due to the error handling nature of promises and the `simple` mode `request-promise` has, wrapping the errors to make a `StatusCodeError` more distinguishable from a `RequestError`, which wraps all errors that come from `request`, makes more sense.
