### ISSUE TITLE
How to use jest mock specified request with request-promise?

### ISSUE THREAD

**Issue by hasyung** [request/request-promise#273]
I want to use jest mock specified request with request-promise. For example: in a method, I want to mock like request-promise(uri_1).mockResolvedValue(resp), but I don't want to mock uri_2 in the same method. What should I do in this situation?

**Comment by hasyung** [comment]
The request-promise is a method, I can't pass parameters in jest.

**Comment by analog-nico** [comment]
I think this is rather a question for `jest`. Please ask them how to mock a function that returns a promise. Once you know this and the specifics of how to only mock the function if certain parameter values are given then you can apply that to `request-promise`. I don’t think there is anything special in addition to general `jest` usage.

Closing this for now since I assume you already found a solution in the past months. Feel free to reopen if you still need a fix.
