### ISSUE TITLE
Lodash error using request promise

### ISSUE THREAD

**Issue by ZECTBynmo** [request/request-promise#49]
While making a get request, I get the following error

"Uncaught TypeError: _.assign is not a function", source: /Users/ZECTbynmo/Projects/ConnectorTester/node_modules/request-promise/lib/rp.js (19)

Any ideas?

**Comment by analog-nico** [comment]
I just ran a unit tests with the latest module versions and they are green.

Which node.js/io.js version and which lodash version do you use?

**Comment by ZECTBynmo** [comment]
I'm running inside of an [electron](https://github.com/atom/electron) app. It's running io.js v2.2.1

**Comment by analog-nico** [comment]
The [Travis CI build](https://travis-ci.org/request/request-promise/jobs/62777434) uses io.js 2.3.0. Maybe the issue is related to the specific environment electron is creating. (However, I never used electron before.)

Are you able to debug the code and look into the `_` object? Somehow the lodash object is not loaded properly.

FYI, all we are talking about is `var _ = require('lodash');` and then the use of assign in `var temp = _.assign({}, require.cache);`.

**Comment by analog-nico** [comment]
@ZECTBynmo Any news regarding this issue? Can I help?

**Comment by analog-nico** [comment]
Please check if you installed lodash correctly. That is all I can tell right now. Please reopen this issue if you need further assistance.
