### ISSUE TITLE
What's considered "large quantities of data"

### ISSUE THREAD

**Issue by Cottin** [request/request-promise#53]
In the docs you write "If you stream large quantities of data the buffer grows big and that has an impact on your memory footprint. In these cases you can just var request = require('request'); and use request for streaming large quantities of data."

Have you done any test on this and is it possible to state in the docs where the typical limit is? Or is it too dependent on environment so that it's up to everyone to test ourselves?

**Comment by analog-nico** [comment]
If you use a stream you would normally expect that only the amount of memory is used as required by the data currently streaming through. For Request this is the case. For Request-Promise, however, the streamed data is buffered internally until the stream finishes. (So that the whole buffer can be passed to the resolved promise - even if you don't make use of the promise.)

If you download a 10MB file for example. Request-Promise always requires 10MB of memory. Request also requires 10MB if you use it with a callback. If you use Request with streaming, however, the memory footprint might be much lower if a downloaded chunk of the file gets garbage collected before a new chunks gets downloaded.

You get the same memory footprint for all Request-Promise calls as if you would use Request with a callback. So if you would be fine using Request with a callback you can as well use Request-Promise with streaming. Or said differently: If you use the streaming just for the programming style you may use it. However, if you use streaming for a better use of your resources you should use Request instead.

Does this help?

**Comment by Cottin** [comment]
Thank you! I get it now. I didn't read the docs too carefully, and I'm not experienced enough with `request` so that "pipe", "stream" or `.pipe` rang a bell. Sorry.

The docs are actually pretty clear: `However, if you want to pipe large amounts...` and then `E.g. you may only use streaming: rp(...).pipe(...)` . I'm fault :)

I'm not to be using streaming so no worries for me. Thanks for a great library!

**Comment by analog-nico** [comment]
The docs indeed assume a lot of knowledge which I certainly can't expect from everyone. My bad. I linked this issue in the README so others may benefit from our discussion as well. Cheers!
