### ISSUE TITLE
docs don't say how to post a payload

### ISSUE THREAD

**Issue by mgenev** [request/request-promise#59]
No offense, but the docs are awful. How do I post a payload? It just gives url as an example...

**Comment by analog-nico** [comment]
Hi @mgenev, I see your point. Theoretically, though, all a user has to do is to go to the [Request README](https://github.com/request/request) because Request-Promise exposes the same API. In any case since you had a bad experience with the docs certainly others do, too.

Since you have fresh eyes: In which section of the README would you expect a link to the Request README? In particular I would link the [request options section](https://github.com/request/request#requestoptions-callback). If that wouldn't be good enough what would you expect from the docs?

**Comment by soplakanets** [comment]
+1 for info on how to send data in docs. This is simply a one additional line, right?

**Comment by analog-nico** [comment]
Hey guys, I updated the post example in the README. However, since @mgenev found the docs being awful I would appreciate your feedback on how to improve them.

**Comment by soplakanets** [comment]
Haha, I wouldn't say they are awful :) 

Thanks!

**Comment by analog-nico** [comment]
;D

**Comment by mgenev** [comment]
Here's a good example https://visionmedia.github.io/superagent/

I knew how to post right away :D

**Comment by ksnyde** [comment]
One thing I found missing was how to set header variables. I imagine this is a very common requirement and I even suspect there's a very easy way to do it but it was not revealed in the docs. :)

**Comment by analog-nico** [comment]
@ksnyde Thanks for the tip. I will mention that in the next version of the docs. BTW, all docs of [Request](https://github.com/request/request) are valid for Request-Promise, too. So [setting headers](https://github.com/request/request#custom-http-headers) is the same.

**Comment by ksnyde** [comment]
yeah in the end I did assume that was the case but busy people are stupid people so being explicit pays off more times than not :)

**Comment by analog-nico** [comment]
+1

**Comment by analog-nico** [comment]
I just released 1.0.0 and with that overhauled the README. Thanks for the feedback all you guys! Let me know if can improve something further.

**Comment by mgenev** [comment]
perfect thanks a lot!
