### ISSUE TITLE
Response caching with request-promise?

### ISSUE THREAD

**Issue by brabster** [request/request-promise#83]
Hi there, a question probably more than an issue here.

I'd like to get my request-promise client to do some rudimentary response caching based on headers, method, url (ideally just observing the response cache headers but not necessary)

I'm not sure where this would be best done or what would be a good library to use? I'm asking here as I can't see a way of plugging in my own possibly wrapped request library and it may be that caching the promise against the request properties is the way to go.

Many thanks!

**Comment by brabster** [comment]
Something like https://www.npmjs.com/package/request-http-cache might fit the bill nicely, but I think I'd need to be able to inject my manipulated request lib into request-promise.

**Comment by analog-nico** [comment]
Hi @brabster from a software design perspective I would write a wrapper which does the caching. Something like:

``` js
var rp = require('request-promise');

var cache = {
    set: function (options, response) { /* ... */ },
    get: function (options) { /* ... */ }
};

module.exports = function rpWithCaching(options) {
    if (!cache.match(options)) {
        cache.set(options, rp(options));
    }
    return cache.get(options);
};
```

Since it is so simple I guess you won't find a package for just that. But of course the solution assumes that you always use Request-Promise through its primary function `rp(options)` and not `rp.get(options)` or `rp.defaults(options)` etc. If you wan't a good solution which allows to still use the full Request-Promise API you would need to dig deep into the internals.

**Comment by brabster** [comment]
Cool, thanks! Didn't want to write it myself if I didn't have to and good to get your view.

**Comment by analog-nico** [comment]
You are welcome.
