### ISSUE TITLE
Failed Request-promise Jasmine2 tests return as successful 

### ISSUE THREAD

**Issue by qualityshepherd** [request/request-promise#87]
I'm trying to add some end point tests to my [Protractor](http://www.protractortest.org/) test suite (using Jasmine 2) but my tests always pass, even when I try to fail them. In the example below, my response has the expected data, but does not fail, even though it should. 

```
it('should return foo, function(done) {
    rp(options).then(function(response) {
        console.log(response.foo); // returns 'foo'
        expect(response.url).toBe('bar'); // should fail but does not
        done();
    });
});
```

**Comment by analog-nico** [comment]
Hi @qualityshepherd, I can't tell for sure because I am using Mocha myself but try this to handle the error thrown by the expect statement:

``` js
it('should return expected video url', function(done) {
    rp(options)
        .then(function(response) {
            console.log(response.foo); // returns 'foo'
            expect(response.url).toBe('bar'); // should fail but does not
            done();
        })
        .catch(function (err) {
            done(err);
        });
});
```

Does this help?

**Comment by qualityshepherd** [comment]
Hi @analog-nico, thanks for the speedy response. I added the catch, but no joy. It still succeeds when it should fail. Strange...

**Comment by analog-nico** [comment]
It was long ago that I switched from Jasmine to Mocha because passing an error to `done()` [was not possible](https://github.com/jasmine/jasmine/issues/567). The workaround would be [to intentionally fail an expectation](http://ng-learn.org/2014/08/Testing_Promises_with_Jasmine/). Since this is ugly the community created [jasmine-promises](https://github.com/matthewjh/jasmine-promises) to [allow returning a promise](https://github.com/jasmine/jasmine/issues/681#issuecomment-147835360) similar to Mocha. However, they later introduced [`done.fail()`](http://jasmine.github.io/edge/introduction.html#section-Asynchronous_Support) which is what you probably want to use in the catch block.

However, judging from your observations your `expect(...)` probably doesn't fail to begin with. Please debug your code and check the variables. If you still face issues you are much better off approaching the Jasmine community and ask about how to handle tests with promises.

Happy debugging!

**Comment by qualityshepherd** [comment]
Thanks @analog-nico. Jasmine2's expect was just never failing. I installed chai and it's expects work as expected.

**Comment by analog-nico** [comment]
Strange indeed. :D
